### ISSUE TITLE
TX power unexpected behavior

### ISSUE THREAD

**Issue by MrBan** [openwrt/mt76#153] opened 2018-02-21 16:06 UTC
Test environment
-----------------------
-   1 AP + 1 STA connected with coax cable + static attenuation
-   channel 5745@20MHz
-   fixed MCS-0
-   no data traffic

Test
-----
Set fixed TX power on the AP with `iw dev wlan0 set txpower fixed X` and measure the corresponding RSSI reported by the STA with `iw dev wlan0 station dump`.
The AP TX power has been increased from 0 to 30 dBm, in steps of 1 dBm. The test has been repeated on different frequencies and with different MCS values, almost with the same outcome.

I expected to see the RSSI on the STA growing almost proportionally, as long as the country regulation limit wasn't reached.
The actual behavior is reported in the following chart.

Test result
--------------
![chart](https://user-images.githubusercontent.com/7239570/36488760-92204542-1724-11e8-9798-78cdcf1f4bb1.png)

**Comment by LorenzoBianconi** [comment] 2018-02-22 07:07
Hi Gaetano,

could you provide more info about your test environment please:
- commit id
- same behaviour on all channels/channel widths?
- what about calibration data?

Moreover in order to get more precise measurements you have to tx data with
duty cycle close (best as you can) to 100% and sniff rx data at the
receiver (rx radiotap contains rx pwr info)

Regards
Lorenzo

Test environment

   - 1 AP + 1 STA connected with coax cable + static attenuation
   - channel 5745@20MHz
   - fixed MCS-0
   - no data traffic

Test

Set fixed TX power on the AP with iw dev wlan0 set txpower fixed X and
measure the corresponding RSSI reported by the STA with iw dev wlan0
station dump.
The AP TX power has been increased from 0 to 30 dBm, in steps of 1 dBm. The
test has been repeated on different frequencies and with different MCS
values, almost with the same outcome.

I expected to see the RSSI on the STA growing almost proportionally, as
long as the country regulation limit wasn't reached.
The actual behavior is reported in the following chart.
Test result

[image: chart]
<https://user-images.githubusercontent.com/7239570/36488760-92204542-1724-11e8-9798-78cdcf1f4bb1.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openwrt/mt76/issues/153>, or mute the thread

**Comment by MrBan** [comment] 2018-02-22 17:20
Here some other test results. This time there was background traffic from AP to STA and 
the RSSI value has been extracted from packets' radiotap on the receiver side (average value over 1000 packets).
For each channel the test has been repeated with different MCS values.

commit id: e50465605266118060df1b86eb7641c65fd29c65
chip: mt7612e

5754@40MHz
-------------------
![chart](https://user-images.githubusercontent.com/7239570/36551784-b2b9f530-17f8-11e8-855f-2dcecab115fe.png)

5180@20MHz
-------------------
![chart 1](https://user-images.githubusercontent.com/7239570/36551822-c7479ee4-17f8-11e8-9a8c-727c0f436fb0.png)

5500@20MHz
-------------------
![chart 2](https://user-images.githubusercontent.com/7239570/36551866-e1bd83ec-17f8-11e8-8cd4-3eca89880bf6.png)

**Comment by LorenzoBianconi** [comment] 2018-02-23 08:35
Hi Gaetano,

thx for your tests. Have you tried to bisect in order to verify if this is a regression?
Regards,
Lorenzo

**Comment by nbd168** [comment] 2018-02-24 09:28
Fixed in the latest version, please test.

**Comment by MrBan** [comment] 2018-02-26 11:30
Definitely better!

Thanks guys.

![chart](https://user-images.githubusercontent.com/7239570/36668205-d25b4fd8-1af0-11e8-8fff-28d7105ac03d.png)

**Closed** 2018-02-26 11:34 UTC
