### ISSUE TITLE
transmit queue 0 timed out

### ISSUE THREAD

**Issue by taeasy** [openwrt/mt76#364] opened 2020-02-23 06:06 UTC
[133025.942765] ------------[ cut here ]------------
[133025.947490] WARNING: CPU: 0 PID: 0 at net/sched/sch_generic.c:320 0x8038b2f0
[133025.954629] NETDEV WATCHDOG: eth0 (mtk_soc_eth): transmit queue 0 timed out
[133025.961648] Modules linked in: pppoe ppp_async pppox ppp_generic nf_conntrack_ipv6 mt76x2e mt76x2_common mt76x02_lib mt7603e mt76 mac80211 iptable_nat ipt_REJECT ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_state xt_nat xt_multiport xt_mark xt_mac xt_limit xt_conntrack xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_FLOWOFFLOAD xt_CT slhc nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_conntrack_ipv4 nf_nat_ipv4 nf_nat nf_log_ipv4 nf_flow_table_hw nf_flow_table nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack iptable_mangle iptable_filter ip_tables crc_ccitt compat ledtrig_usbport nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables ip6t_REJECT x_tables nf_reject_ipv6 leds_gpio xhci_plat_hcd xhci_pci xhci_mtk xhci_hcd gpio_button_hotplug usbcore nls_base usb_common
[133026.032525] CPU: 0 PID: 0 Comm: swapper/0 Not tainted 4.14.167 #0
[133026.038682] Stack : 00000000 00000000 00000000 8fdfab40 00000000 00000000 00000000 00000000
[133026.047107]         00000000 00000000 00000000 00000000 00000000 00000001 8fc09d60 ac07f5be
[133026.055525]         8fc09df8 00000000 00000000 00006cd0 00000038 8049b6d8 00000008 00000000
[133026.063943]         00000000 80550000 00007f0d 70617773 8fc09d40 00000000 00000000 80509e3c
[133026.072361]         8038b2f0 00000140 00000000 8fdfab40 00000008 802ac758 00000000 806b0000
[133026.080779]         ...
[133026.083301] Call Trace:
[133026.083358] [<8049b6d8>] 0x8049b6d8
[133026.089429] [<8038b2f0>] 0x8038b2f0
[133026.092989] [<802ac758>] 0x802ac758
[133026.096547] [<8000c1a0>] 0x8000c1a0
[133026.100102] [<8000c1a8>] 0x8000c1a8
[133026.103657] [<80484544>] 0x80484544
[133026.107212] [<800719f0>] 0x800719f0
[133026.110774] [<8002e5f8>] 0x8002e5f8
[133026.114330] [<8038b2f0>] 0x8038b2f0
[133026.117893] [<8002e680>] 0x8002e680
[133026.121457] [<8038b2f0>] 0x8038b2f0
[133026.125013] [<80099860>] 0x80099860
[133026.128572] [<8038b144>] 0x8038b144
[133026.132128] [<8008842c>] 0x8008842c
[133026.135683] [<8005f15c>] 0x8005f15c
[133026.139243] [<800886e8>] 0x800886e8
[133026.142799] [<80079038>] 0x80079038
[133026.146360] [<804a24d8>] 0x804a24d8
[133026.149918] [<80032f84>] 0x80032f84
[133026.153475] [<80259e70>] 0x80259e70
[133026.157032] [<80007488>] 0x80007488
[133026.160584] 
[133026.162281] ---[ end trace 69a7b5c42d35e6a0 ]---
[133026.167010] mtk_soc_eth 1e100000.ethernet eth0: transmit timed out

**Comment by ynezz** [comment] 2020-02-23 07:51
This is not related to this sub-project and it's duplicate of #211 which was probably somehow fixed in https://github.com/openwrt/openwrt/commit/c8f8e59816eca49d776562d2d302bf990a87faf0

**Closed by ynezz** 2020-02-23 07:51 UTC
