### ISSUE TITLE
7603

### ISSUE THREAD

**Issue by 2324059** [openwrt/mt76#34] opened 2016-05-10 07:43 UTC
root@sh:/# [ 1428.380000] ------------[ cut here ]------------
[ 1428.380000] WARNING: CPU: 1 PID: 2909 at /home/sh/sh03/openwrt/build_dir/target-mipsel_1004kc+dsp_uClibc-0.9.33.2/linux-ramips_mt7621/mt76-2016-03-04/mt7603_mac.c:1190 mt7603_mac_work+0xe8/0x288 [mt7603e]()
[ 1428.420000] Modules linked in: pppoe ppp_async iptable_nat pptp pppox ppp_mppe ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_quota xt_pkttype xt_owner xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_id xt_hl xt_ecn xt_dscp xt_conntrack xt_comment xt_addrtype xt_TCPMSS xt_REDIRECT xt_NETMAP xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY slhc nf_reject_ipv4 nf_nat_masquerade_ipv4 nf_nat_ftp nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache nf_conntrack_ftp nf_conntrack iptable_raw iptable_mangle iptable_filter ipt_ECN ip_tables crc_ccitt mt7603e mt76x2e mt76 mac80211 cfg80211 compat ledtrig_usbdev ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_raw ip6table_mangle ip6table_filter ip6_tables x_tables ip_gre gre ip_tunnel tun ipv6 sha1_generic ecb arc4 crypto_blkcipher mmc_block sdhci_pltfm sdhci mtk_sd mmc_core leds_gpio xhci_plat_hcd xhci_hcd ahci libahci libata sd_mod scsi_mod gpio_button_hotplug usbcore nls_base usb_common aead crypto_hash
[ 1428.610000] CPU: 1 PID: 2909 Comm: kworker/u8:0 Not tainted 3.18.29 #3
[ 1428.620000] Workqueue: phy1 mt7603_mac_work [mt7603e]
[ 1428.630000] Stack : 00000000 00000004 00000006 00000001 00000000 00000001 00000000 00000000
          8eab6500 802d8824 00000000 8ec4d190 000004a6 00000000 8f804814 8f804800
          00000088 8005a380 80384468 80040e34 8f804814 8f804800 802ff7b8 8f859d64
          8f859d64 800291d4 80340e60 8003e5a8 802dc474 00000000 00000477 00000000
          00000000 00000000 00000000 00000000 00000000 00000000 31796870 00000000
          ...
[ 1428.700000] Call Trace:
[ 1428.710000] [<800160c0>] show_stack+0x50/0x84
[ 1428.720000] [<8015dedc>] dump_stack+0x88/0xc0
[ 1428.730000] [<800292dc>] warn_slowpath_common+0x84/0xb4
[ 1428.740000] [<80029394>] warn_slowpath_null+0x18/0x24
[ 1428.750000] [<8ec4d190>] mt7603_mac_work+0xe8/0x288 [mt7603e]
[ 1428.760000] [<8003c118>] process_one_work+0x218/0x354
[ 1428.770000] [<8003cac0>] worker_thread+0x2d8/0x448
[ 1428.780000] [<80040870>] kthread+0xd8/0xe4
[ 1428.790000] [<80005878>] ret_from_kernel_thread+0x14/0x1c
[ 1428.800000] 
[ 1428.800000] ---[ end trace 5df2a396188f9de3 ]---

**Comment by nbd168** [comment] 2017-03-15 20:05
Duplicate of #32

**Closed by nbd168** 2017-03-15 20:05 UTC
