### ISSUE TITLE
MT7603 crashes in station mode

### ISSUE THREAD

**Issue by dangowrt** [openwrt/mt76#42] opened 2016-08-10 13:06 UTC
```
[   20.870000] MCU message 40 (seq 12) timed out
[   21.870000] MCU message 8 (seq 13) timed out
[   22.870000] MCU message 40 (seq 14) timed out
[   22.870000] ------------[ cut here ]------------
[   22.870000] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready
[   22.880000] WARNING: CPU: 0 PID: 31 at /usr/src/lede/build_dir/target-mipsel_1004kc_musl-1.1.15/linux-ramips_mt7621/mt76-2016-07-08)
[   22.900000] Modules linked in: pppoe ppp_async iptable_nat pppox ppp_generic nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REn
[   22.970000] CPU: 0 PID: 31 Comm: kworker/u8:2 Not tainted 4.4.15 #2
[   22.970000] Workqueue: phy1 mt7603_mac_work [mt7603e]
[   22.970000] Stack : 8fd18200 80450000 803d29b8 000004a9 8f24d1ac 00000000 8fc04614 8fd18218
          00000088 80063bec 803d29b8 00000000 0000001f 804a367c 803ee17c 8fd59d54
          80450000 80061938 80450000 804c0000 80458174 80458178 803d72cc 8fd59d54
          80450000 800411e4 8fc04614 8fd59d8c 00000400 00000000 00000000 00d59d74
          8f24d0c4 8ff40500 8ff40700 31796870 00000000 00000000 00000000 00000000
          ...
[   22.970000] Call Trace:
[   22.970000] [<8001665c>] show_stack+0x50/0x84
[   22.970000] [<801ad680>] dump_stack+0x84/0xbc
[   22.970000] [<8002bee8>] warn_slowpath_common+0xa0/0xd0
[   22.970000] [<8002bfa0>] warn_slowpath_null+0x18/0x24
[   22.970000] [<8f24d1ac>] mt7603_mac_work+0xe8/0x27c [mt7603e]
[   22.970000] [<8003ee10>] process_one_work+0x214/0x358
[   22.970000] [<8003fd0c>] worker_thread+0x2d8/0x440
[   22.970000] [<800444c4>] kthread+0xd8/0xec
[   22.970000] [<80005478>] ret_from_kernel_thread+0x14/0x1c
[   22.970000] 
[   23.070000] ---[ end trace ce7a54bcc146d0e3 ]---
```

**Comment by nbd168** [comment] 2017-03-15 20:06
Duplicate of #32

**Closed by nbd168** 2017-03-15 20:06 UTC
